version: '3.3'

services:

  nuvola:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: nuvola
      MYSQL_PASSWORD: nuvola
      MYSQL_DATABASE: nuvola
      MYSQL_ALLOW_EMPTY_PASSWORD: "True"
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  php-fpm:
    build: .
    ports:
      - 9000:8000
    volumes:
      - ./:/var/www/html
    depends_on: 
      - nuvola
    command: bash -c 'symfony server:start'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         

    
  
